### ISSUE TITLE
Unable to connect to a repository at URL 'https://svn.parrot.org/parrot/trunk'

### ISSUE THREAD

**Issue by jbrahy** [bschmalhofer/pipp#7]
Is there a new repository for parrot? I see that it's also hosted on git here: git://github.com/parrot/parrot.git

Is there something different about the svn repo?

perl Configure.pl --gen-parrot  
Checking out Parrot r38035 via svn...
svn: E175013: Unable to connect to a repository at URL 'https://svn.parrot.org/parrot/trunk'
svn: E175013: Access to 'https://svn.parrot.org/parrot/trunk' forbidden
Unable to locate parrot_config.
To automatically checkout (svn) and build a copy of parrot,
try re-running Configure.pl with the '--gen-parrot' option.
Or, use the '--parrot-config' option to explicitly specify
the location of parrot_config.
Use of uninitialized value $make in system at build/gen_parrot.pl line 68.
Unable to locate parrot_config.
To automatically checkout (svn) and build a copy of parrot,
try re-running Configure.pl with the '--gen-parrot' option.
Or, use the '--parrot-config' option to explicitly specify
the location of parrot_config.

**Comment by bschmalhofer** [comment]
Current development of Parrot is taking place in git. As far as I remember, when I worked on Pipp I had the code already hosted here on Github, while Parrot was still in Subversion. As I had stopped working on Pipp, I never bothered to update the build process.

Pipp never got very far. If you are interested in implementing PHP, I'd advise you to make a fresh start and do the implementation using NQP.
